import mysql.connector as con
mydb = con.connect(host="localhost",user="root",passwd="KARAN&vivo99")
cur=mydb.cursor()
cur.execute('create database if not exists MPS')
mydb.close()
cur.close()

mydb = con.connect(host="localhost",user="root",passwd="KARAN&vivo99",database="MPS")
cur=mydb.cursor()
query="drop table if exists admission"
cur.execute(query)
cur.execute("drop table if exists Admission")
cur.execute("drop table if exists student")
cur.execute("drop table if exists Student")
cur.execute("drop table if exists fees")
cur.execute("drop table if exists Fees")

cur.execute("CREATE TABLE Fees(adno varchar(10),FeeDeposit varchar(20),Month varchar(10))")
cur.execute("insert into Fees values('101','5000','April')")
cur.execute("insert into Fees values('101','5000','May')")
cur.execute("insert into Fees values('101','5000','June')")
cur.execute("insert into Fees values('101','5000','July')")
cur.execute("insert into Fees values('102','5000','April')")
cur.execute("insert into Fees values('102','5000','May')")
cur.execute("insert into Fees values('102','5000','June')")
cur.execute("insert into Fees values('102','5000','July')")
cur.execute("insert into Fees values('102','5000','August')")
cur.execute("insert into Fees values('103','5000','April')")
cur.execute("insert into Fees values('103','5000','May')")
cur.execute("insert into Fees values('103','5000','June')")
cur.execute("insert into Fees values('103','5000','July')")
cur.execute("insert into Fees values('104','5000','April')")
cur.execute("insert into Fees values('104','5000','May')")
cur.execute("insert into Fees values('104','5000','June')")
cur.execute("insert into Fees values('105','5000','April')")
cur.execute("insert into Fees values('105','5000','May')")
mydb.commit()
mydb.close()
cur.close()

mydb = con.connect(host="localhost",user="root",passwd="KARAN&vivo99",database="MPS")
cur=mydb.cursor()
cur.execute("CREATE TABLE Admission(adno varchar(10) unique,rno varchar(10),sname varchar(50),address varchar(100),phon varchar(20),clas varchar(10))")
cur.execute("insert into Admission values('101','1','Aman Dhattarwal','Delhi','761551876','XII')")
cur.execute("insert into Admission values('102','2','Monica Trivedi','Delhi','736662822','XII')")
cur.execute("insert into Admission values ('103','3','Gaurav Pandey','Delhi','882678016','XII')")
cur.execute("insert into Admission values('104','4','Pravendra Tomar','Lucknow','823836363','XII')")
cur.execute("insert into Admission values('105','5','Tarak Mehta','Mumbai','922772637','XII')")
mydb.commit()
mydb.close()
cur.close()

mydb = con.connect(host="localhost",user="root",passwd="KARAN&vivo99",database="MPS")
cur=mydb.cursor()
cur.execute("CREATE TABLE Student(session varchar(30),stname varchar(50),stclass varchar(10), stsec varchar(10), stroll varchar(5) unique,sub1 varchar(20),sub2 varchar(20),sub3 varchar(20))")
cur.execute("insert into Student values('2019-2020','Abhimanyu Singh','X','A','1','English','Maths','Science')")
cur.execute("insert into Student values('2019-2020','Aditi Yadav','X','A','2','English','French','Science')")
cur.execute("insert into Student values('2019-2020','Krishna Murari','X','A','3','English','Maths','Social Science')")
cur.execute("insert into Student values('2019-2020','Ram Charan','X','A',4,'English','Maths','Computer')")
cur.execute("insert into Student values('2019-2020','Vikas Yadav','X','A','5','Hindi','Maths','Science')")
cur.execute("insert into Student values('2019-2020','Yashraj Verma','X','B','6','English','Computer','Science')")
cur.execute("insert into Student values('2019-2020','Zaid Khan','X','C','7','English','Maths','Hindi')")
cur.execute("insert into Student values('2019-2020','Alakh Pandey','XII','A','10','English','Maths','Biology')")
cur.execute("insert into Student values('2019-2020','Naman Rajbhar','XII','A','11','Physics','Chemistry','Computer')")
mydb.commit()
mydb.close()
cur.close()

print ("Data has been entered successfully!!!!")
